title: UniMakers CDR 2026
description: Documentation de l'association UniMakers pour la CDR 2026
theme: just-the-docs
color_scheme: unimakers

url: https://unimakers.fr/CDR2026Docs/

nav_external_links:
  - title: <- Return to website
    url: https://unimakers.fr
aux_links:
  GitHub d'UniMakers: https://github.com/UniMakers
